; colocando etiquetas para os pinos e definindo registradores
.equ DISPLAY = PORTD
.equ flagA = PC5
.equ flagB = PC4
.equ flagC = PC3
.equ flagD = PC2
.equ LEDVITORIA = PC1
.equ LEDVERM = PC0
.equ LEDPRET = PB5
.equ LEDVERDE = PB4
.equ BOTAOSORTEIO = PD2
.equ BOTAOMODO = PB0
.equ BOTAOINC = PB1
.equ BOTAODEC = PB2
.equ BOTAOROLETAR = PB3
.def dezena = R20
.def unidade = R21
.def flagModo = R22
.def flagSorteio = R23
.def flagLoop = R17
.def AUX = R16
.def AUXB = R24
.def resultado = R25
.def contador = R18
.def numEscolhido = R19

